<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Drawing" />
    <Reference Include="Twinsanity">
      <HintPath>..\twinsanity-editor\Twinsanity\bin\Release\Twinsanity.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
