"""Names the constructors that belong to exactly one script command or condition.

A builder like `BuildCommand_GetShortRoute` allocates its object and hands it to a constructor that nothing
else calls. That constructor is the command's, and nothing about it needs reading: if exactly one named
builder calls a function, the name follows from the builder's.

The rule is deliberately strict in the way that matters: **exactly one builder** among the callers. A
constructor usually has a second caller - its own destructor, or the sibling that reuses it - and that is
fine, but a helper shared between two commands is not either command's constructor, and naming it after one
of them would be worse than leaving it blank. Builders that share a constructor (NowTurnLeft and NowTurnRight
do) therefore name nothing, which is correct. Anything with more than four callers is a general helper, not
a constructor, whatever its callers are called.

  python tools/re/ctors.py [--dry]
"""
import argparse, collections, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
DECOMP = os.path.join(ROOT, "tools", "ghidra", "SLES_525.68.c")
OUT = os.path.join(HERE, "db", "ctors.tsv")

BUILDER = re.compile(r"^Build(Command|Condition)_(\w+)$")


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--dry", action="store_true")
    o = ap.parse_args()

    text = open(DECOMP, encoding="utf-8", errors="replace").read()
    heads = [(int(m.group(1), 16), m.group(2), m.start()) for m in
             re.finditer(r"^//// ([0-9a-f]{8}) (\S+)$", text, re.M)]
    heads.sort()
    names = {a: n for a, n, _ in heads}

    callers = collections.defaultdict(set)
    for i, (addr, name, pos) in enumerate(heads):
        end = heads[i + 1][2] if i + 1 < len(heads) else len(text)
        for m in re.finditer(r"\bFUN_([0-9a-f]{8})\s*\(", text[pos:end]):
            callers[int(m.group(1), 16)].add(addr)

    known = set()
    for f in os.listdir(os.path.join(HERE, "db")):
        if not f.endswith(".tsv"): continue
        for line in open(os.path.join(HERE, "db", f), encoding="utf-8", errors="replace"):
            parts = line.split("\t")
            if len(parts) >= 2 and parts[1].strip() == "F":
                try: known.add(int(parts[0], 16))
                except ValueError: pass

    rows, skipped = [], collections.Counter()
    for addr, who in callers.items():
        if addr in known or not names.get(addr, "").startswith("FUN_"): continue
        if len(who) > 4:
            skipped["too many callers to be a constructor"] += 1
            continue
        builders = [names[c] for c in who if BUILDER.match(names.get(c, ""))]
        if len(builders) != 1:
            skipped["no builder among the callers" if not builders else "several builders share it"] += 1
            continue
        m = BUILDER.match(builders[0])
        rows.append((addr, f"Init{m.group(2)}{m.group(1)}", f"the constructor {builders[0]} calls"))

    seen = collections.Counter(n for _, n, _ in rows)
    rows = [r for r in rows if seen[r[1]] == 1]
    print(f"constructors with exactly one builder caller: {len(rows)}")
    print("  skipped: " + ", ".join(f"{k} {v}" for k, v in skipped.most_common()))
    if o.dry:
        for addr, name, note in sorted(rows)[:20]: print(f"   {addr:08x}  {name}")
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# Generated by tools/re/ctors.py: functions whose only caller is a named script command or\n"
                "# condition builder, so the constructor belongs to that command. Do not edit: regenerate.\n"
                "# address\tkind\tname\tdetail\n")
        for addr, name, note in sorted(rows):
            f.write(f"{addr:08x}\tF\t{name}\t{note}\n")
    print(f"wrote {len(rows)} names to {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
