// Headless Ghidra script: exports the whole annotation layer of the program to text files that live in git.
// Args: OUTDIR.  Writes symbols.tsv, comments.tsv and types.h.  ImportDb.java reads the first two back.
//
// The Ghidra project itself (tools/ghidra/project) is a binary blob that is not in version control and is
// rebuilt from twinsanity-reversed's .gar.  Everything we learn about the executable therefore has to live
// outside it, or it is lost the next time that archive is re-restored.
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressIterator;
import ghidra.program.model.data.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.*;
import java.io.PrintWriter;
import java.util.*;

public class ExportDb extends GhidraScript {

    /** Names Ghidra invented itself - FUN_00123456, DAT_0030a480, LAB_, switchD_ ... - carry no information. */
    static boolean isAuto(String n) {
        return n.matches("(FUN|DAT|LAB|SUB|EXT|UNK|SWITCH|OFF|PTR|ARRAY|s|u)_[0-9a-fA-F]{4,}.*")
            || n.startsWith("caseD_") || n.startsWith("switchD_");
    }

    @Override
    public void run() throws Exception {
        String dir = getScriptArgs()[0];
        Listing listing = currentProgram.getListing();
        int fn = 0, lab = 0, com = 0;

        try (PrintWriter out = new PrintWriter(dir + "/symbols.tsv", "UTF-8")) {
            out.println("# Names for Crash Twinsanity's PAL executable (SLES_525.68), applied by tools/re/ghidra.py import.");
            out.println("# address\tkind\tname\tdetail        kind F = function (detail = prototype), L = label (detail = data type)");
            for (Function f : currentProgram.getFunctionManager().getFunctions(true)) {
                if (isAuto(f.getName())) continue;
                out.println(f.getEntryPoint() + "\tF\t" + f.getName() + "\t" + f.getSignature().getPrototypeString());
                fn++;
            }
            for (Symbol s : currentProgram.getSymbolTable().getAllSymbols(true)) {
                if (s.getSource() == SourceType.DEFAULT || s.getSymbolType() == SymbolType.FUNCTION) continue;
                if (isAuto(s.getName())) continue;
                Data d = listing.getDataAt(s.getAddress());
                out.println(s.getAddress() + "\tL\t" + s.getName() + "\t" + (d == null ? "" : d.getDataType().getName()));
                lab++;
            }
        }

        try (PrintWriter out = new PrintWriter(dir + "/comments.tsv", "UTF-8")) {
            out.println("# address\tkind\ttext        kind 3 = plate, 1 = pre, 0 = end of line, 2 = post; newlines escaped");
            for (int type : new int[]{CodeUnit.PLATE_COMMENT, CodeUnit.PRE_COMMENT,
                                      CodeUnit.EOL_COMMENT, CodeUnit.POST_COMMENT}) {
                AddressIterator it = listing.getCommentAddressIterator(type, currentProgram.getMemory(), true);
                while (it.hasNext()) {
                    Address a = it.next();
                    String c = listing.getComment(type, a);
                    if (c == null || c.isEmpty()) continue;
                    out.println(a + "\t" + type + "\t" + c.replace("\\", "\\\\").replace("\n", "\\n"));
                    com++;
                }
            }
        }

        try (PrintWriter out = new PrintWriter(dir + "/types.h", "UTF-8")) {
            out.println("/* Structs, unions, enums and typedefs defined in the Ghidra project.");
            out.println("   Generated by tools/re/ExportDb.java - never compiled, kept for reading and diffing. */");
            List<DataType> types = new ArrayList<>();
            currentProgram.getDataTypeManager().getAllDataTypes(types);
            types.removeIf(t -> t.getPathName().startsWith("/generic_clib")
                             || t instanceof Pointer || t instanceof Array || t instanceof BuiltInDataType);
            types.sort(Comparator.comparing(DataType::getPathName));
            new DataTypeWriter(currentProgram.getDataTypeManager(), out).write(types, monitor);
        }

        println("exported " + fn + " functions, " + lab + " labels, " + com + " comments");
    }
}
